filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
    - versionStream/src/fake-secrets.yaml.gotmpl
repositories:
- name: doesnotexist
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: cdf
  url: https://cdfoundation.github.io/tekton-helm-chart
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://charts.helm.sh/stable
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
releases:
- chart: jenkins-x/jxboot-helmfile-resources
  version: 1.0.16
  name: jxboot-helmfile-resources
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- chart: jx3/jenkins-x-crds
  version: 3.0.5
  name: jenkins-x-crds
  namespace: jx
  values:
  - versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
- chart: cdf/tekton-pipeline
  version: 0.18.0-1
  name: tekton-pipeline
  namespace: tekton-pipelines
  values:
  - versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
- chart: jx3/jx-pipelines-visualizer
  version: 0.0.52
  name: jx-pipelines-visualizer
  namespace: jx
  values:
  - versionStream/charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
- chart: jx3/jx-preview
  version: 0.0.116
  name: jx-preview
  namespace: jx
- chart: jenkins-x/lighthouse
  version: 0.0.874
  name: lighthouse
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
- chart: jenkins-x/bucketrepo
  version: 0.1.44
  name: bucketrepo
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/bucketrepo/values.yaml.gotmpl
- chart: jx3/jx-build-controller
  version: 0.0.14
  name: jx-build-controller
  namespace: jx
  values:
  - versionStream/charts/jx3/jx-build-controller/values.yaml.gotmpl
- chart: jx3/local-external-secrets
  version: 0.0.6
  name: local-external-secrets
  namespace: jx
- chart: dev/jx3-demoapp5
  version: 0.0.32
  name: jx3-demoapp5
  namespace: jx-staging
- chart: dev/jx3-demoapp6
  version: 0.0.4
  name: jx3-demoapp6
  namespace: jx-staging
- chart: dev/jx3-demoapp5
  version: 0.0.31
  name: jx3-demoapp5
  namespace: jx-production
- chart: dev/jx3-demoapp6
  version: 0.0.4
  name: jx3-demoapp6
  namespace: jx-production
- chart: dev/jx3-demoapp1
  version: 0.0.5
  name: jx3-demoapp1
  namespace: jx-staging
- chart: dev/jx3-demoapp4
  version: 1.0.6
  name: jx3-demoapp4
  namespace: jx-staging
- chart: dev/jx3-springdemo2
  version: 1.0.12
  name: jx3-springdemo2
  namespace: jx-staging
templates: {}
missingFileHandler: ""
