apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        myriad-personal/env-jx3-openshift3: true
        myriad-personal/jx3-demoapp-py1: true
        myriad-personal/jx3-demoapp1: true
        myriad-personal/jx3-demoapp5: true
    plank: {}
    pod_namespace: jx
    postsubmits:
      troyhart/blox-framework:
      - agent: tekton-pipeline
        branches:
        - master
        - main
        labels:
          aadpodidbinding: tekton-bot
        name: release
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
    presubmits:
      troyhart/blox-framework:
      - agent: tekton-pipeline
        always_run: true
        context: pr-build
        labels:
          aadpodidbinding: tekton-bot
        name: pr-build
        pipeline_run_spec:
          pipelineRef:
            name: jx-meta-pipeline
          serviceAccountName: tekton-bot
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        myriad-personal/env-jx3-openshift3: merge
        myriad-personal/jx3-demoapp-py1: merge
        myriad-personal/jx3-demoapp1: merge
        myriad-personal/jx3-demoapp5: merge
        troyhart/blox-framework: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - myriad-personal/env-jx3-openshift3
        - myriad-personal/jx3-demoapp-py1
        - myriad-personal/jx3-demoapp1
        - myriad-personal/jx3-demoapp5
        - troyhart/blox-framework
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - myriad-personal/env-jx3-openshift3
        - myriad-personal/jx3-demoapp-py1
        - myriad-personal/jx3-demoapp1
        - myriad-personal/jx3-demoapp5
        - troyhart/blox-framework
      target_url: http://dashboard-jx.apps.os.swe-test.aws.myriad.com
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
