apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - myriad-personal/env-jx3-openshift3
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - myriad-personal/jx3-demoapp-py1
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - myriad-personal/jx3-demoapp1
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - myriad-personal/jx3-demoapp2
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - myriad-personal/jx3-demoapp4
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - myriad-personal/jx3-demoapp5
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - myriad-personal/jx3-demoapp6
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - myriad-personal/jx3-springdemo1
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - myriad-personal/jx3-springdemo2
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      myriad-personal/env-jx3-openshift3:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      myriad-personal/jx3-demoapp-py1:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      myriad-personal/jx3-demoapp1:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      myriad-personal/jx3-demoapp2:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      myriad-personal/jx3-demoapp4:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      myriad-personal/jx3-demoapp5:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      myriad-personal/jx3-demoapp6:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      myriad-personal/jx3-springdemo1:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      myriad-personal/jx3-springdemo2:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - myriad-personal/env-jx3-openshift3
      trusted_org: todo
    - repos:
      - myriad-personal/jx3-demoapp-py1
      trusted_org: todo
    - repos:
      - myriad-personal/jx3-demoapp1
      trusted_org: todo
    - repos:
      - myriad-personal/jx3-demoapp2
      trusted_org: todo
    - repos:
      - myriad-personal/jx3-demoapp4
      trusted_org: todo
    - repos:
      - myriad-personal/jx3-demoapp5
      trusted_org: todo
    - repos:
      - myriad-personal/jx3-demoapp6
      trusted_org: todo
    - repos:
      - myriad-personal/jx3-springdemo1
      trusted_org: todo
    - repos:
      - myriad-personal/jx3-springdemo2
      trusted_org: todo
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
