# Source: jx3-demoapp6/templates/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx3-demoapp6-jx3-demoapp6
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
